@startuml

' RMS stands for Recycling Management System
' package onion.lifeproducts.rms {

	class Product {
		- String name
		- float weight
		- ProductCategory category
		- LocalDateTime manufactureDate
		- LocalDateTime endDate
		- Material[] materials

		' + getName(): String
		' + getWeight(): float
		' + getCategory(): String
		' + getManufactureDate(): LocalDateTime
		' + getMaterials(): Material[]
		' + setName(String name): void
		' + setWeight(float weight): void
		' + setCategory(String category): void
		' + setManufactureDate(LocalDateTime manufactureDate): void
		' + setMaterials(Material[] materials): void

	}

	class Material {
		- String name
		- float recycleRate
		- float burnEnvironmentImpact
		- float decayEnvironmentImpact
		- LocalTime burnTime
		- LocalTime decayTime
		- RecyclingGuidance recyclingInstruction

		' + getName(): String
		' + getRecycleRate(): float
		' + getBurnEnvironmentImpact(): float
		' + getDecayEnvironmentImpact(): float
		' + getBurnTime(): LocalTime
		' + getDecayTime(): LocalTime
		' + getRecyclingInstruction(): String
		' + setName(String name): void
		' + setRecycleRate(float recycleRate): void
		' + setBurnEnvironmentImpact(float burnEnvironmentImpact): void
		' + setDecayEnvironmentImpact(float decayEnvironmentImpact): void
		' + setBurnTime(LocalTime burnTime): void
		' + setDecayTime(LocalTime decayTime): void
		' + setRecyclingInstruction(RecyclingGuidance recyclingInstruction): void

	}

	class ProductCategory {
		- String type
	}

	class RecyclingGuidance {
		- String guide
	}

	class RecyclingService {

	}

	class RecyclingCategory {
		- String type

	}

	class ImpactReport {
		- LocalDateTime generatedAt
	}

	class ImpactCalculationStrategy {

	}

	class ConsoleUI {

	}

	class StoragePool {

	}


' }

Product "0..*" *-- "1..*" Material : references
Product "1..1" o-- "0..1" ImpactCalculationStrategy
Product "1..1" *-- "1..1" ProductCategory
Product "1..1" --> "0..*" ImpactReport : generates

Material "1..1" *-- "1..1" RecyclingGuidance
Material "1..1" *-- "1..1" RecyclingCategory

RecyclingGuidance "1..1" *-- "1..1" RecyclingService

StoragePool "1..*" o-  "0..*" Product
StoragePool "1..*" o- "0..*" ProductCategory
StoragePool "1..*" o-- "0..*" Material
StoragePool "1..*" o-  "0..*" RecyclingCategory

ConsoleUI "1..1" --> "0..*" StoragePool : uses

@enduml
