@startuml

' RMS stands for Recycling Management System
' package onion.lifeproducts.rms {

	class Product {
		- Integer id
		- String name
		- ProductCategory category
		- Material[] materials
		- LocalDateTime manufactureDate
		- LocalDateTime endDate
		
		' + getId(): Integer
		' + getName(): String
		' + getCategory(): String
		' + getManufactureDate(): LocalDateTime
		' + getEndDate(): LocalDateTime
		' + getMaterials(): Material[]
		' + setId(Integer id): void
		' + setName(String name): void
		' + setCategory(String category): void
		' + setManufactureDate(LocalDateTime manufactureDate): void
		' + setEndDate(LocalDateTime endDate): void
		' + setMaterials(Material[] materials): void
	}

	class Material {
		- String name
    - float recycleRate
		- float burnAtmosphereImpact
		- float decayAtmosphereImpact
		- float decayGroundImpact
		- float burnEnvironmentImpact
		- float decayEnvironmentImpact
		- LocalDateTime burnTime
		- LocalDateTime decayTime
    - LocalDateTime decayTime
		- RecyclingGuidance recyclingInstruction

		' + getName(): String
		' + getRecycleRate(): float
		' + getBurnEnvironmentImpact(): float
		' + getDecayEnvironmentImpact(): float
		' + getBurnAtmosphereImpact(): float
		' + getDecayAtmosphereImpact(): float
		' + getDecayGroundImpact(): float
		' + getBurnTime(): LocalTime
		' + getDecayTime(): LocalDateTime
		' + getRecyclingInstruction(): String
		' + setName(String name): void
		' + setRecycleRate(float recycleRate): void
		' + setBurnAtmosphereImpact(float burnAtmosphereImpact): void
		' + setDecayAtmosphereImpact(float decayAtmosphereImpact): void
		' + setDecayGroundImpact(float decayGroundImpact): void
		' + setBurnEnvironmentImpact(float burnEnvironmentImpact): void
		' + setDecayEnvironmentImpact(float decayEnvironmentImpact): void
		' + setBurnTime(LocalTime burnTime): void
		' + setDecayTime(LocalTime decayTime): void
		' + setRecyclingInstruction(RecyclingGuidance recyclingInstruction): void

	}

	class ProductCategory {
		- String type
	}

	class RecyclingGuidance {
		- String guide
	}

	class RecyclingService {

	}


	class RecyclingCategory {
		- String type

	}

	class ImpactReport {
		- LocalDateTime generatedAt
	}

	class ImpactCalculationStrategy {

	}

	class ConsoleUI {

	}

	class StoragePool {

	}


' }

Product "0..*" *-- "1..*" Material : uses
Product "1..1" o-- "0..1" ImpactCalculationStrategy : uses
Product "1..1" *-- "1..1" ProductCategory : has
Product "1..1" --> "0..*" ImpactReport : generates

Material "1..1" *-- "1..1" RecyclingGuidance : has
Material "1..1" *-- "1..1" RecyclingCategory

RecyclingGuidance "1..1" *-- "1..1" RecyclingService

StoragePool "1..*" o-  "0..*" Product
StoragePool "1..*" o- "0..*" ProductCategory
StoragePool "1..*" o-- "0..*" Material
StoragePool "1..*" o-  "0..*" RecyclingCategory

ConsoleUI "1..1" --> "0..*" StoragePool : uses


@enduml
